# -*- coding: utf-8 -*-
"""Oficina

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEYaGWfA2AwkZSIqPj7S6NFEKpX2ICtx
"""

import json # importa o modulo JSON
import os

with open('Json_Aula_Python.txt', 'r', encoding='utf-8') as arquivo:
  conteudo = arquivo.read()

dados = json.loads(conteudo)

with open('Json_Aula_Python.json', 'w') as file:
  json.dump(dados, file, indent=4)

def nome_programa():
 print("""


────────────────────────────────────────────────────────────────────────
─██████████─██████████████─██████████████─██████████████─████████████───
─██░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░████─
─████░░████─██░░██████████─██░░██████░░██─██░░██████░░██─██░░████░░░░██─
───██░░██───██░░██─────────██░░██──██░░██─██░░██──██░░██─██░░██──██░░██─
───██░░██───██░░██████████─██░░██──██░░██─██░░██──██░░██─██░░██──██░░██─
───██░░██───██░░░░░░░░░░██─██░░██──██░░██─██░░██──██░░██─██░░██──██░░██─
───██░░██───██░░██████████─██░░██──██░░██─██░░██──██░░██─██░░██──██░░██─
───██░░██───██░░██─────────██░░██──██░░██─██░░██──██░░██─██░░██──██░░██─
─████░░████─██░░██─────────██░░██████░░██─██░░██████░░██─██░░████░░░░██─
─██░░░░░░██─██░░██─────────██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░████─
─██████████─██████─────────██████████████─██████████████─████████████───
────────────────────────────────────────────────────────────────────────
  """)

def exibir_opçoes():
  print('1.Lanches')
  print('2.Restaurantes')
  print('3.Ver Lanche')
  print('4.Ver Restaurante')
  print('5.Adicionar item')
  print('6.Remover item')
  print('7.Salvar')
  print('8.Sair')

def lanches_e_itens():
  #print(dados ['Item'])
 for item in dados:
    print(item["Item"])

def restaurantes():
  #print(dados ['Company'])
  restaurante = []
  for item in dados:
    if item["Company"] not in restaurante:
      restaurante.append(item['Company'])
  print(restaurante)

def menu():

  opcao = input("Digite a opção desejada: ")
  match opcao:
    case '1':
      #código para exibir lanches
      lanches_e_itens()
    case '2':
      #código para exibir restaurantes
      restaurantes()
    case '3':
      # código para ver um lanche expecifico
      ver_lanche()
    case '4':
      # código para ver um restaurante expecifico
      ver_restaurante()
    case '5':
      # código para adicionar item
      adicionar_item()
      print("Adicionando item...")
    case '6':
      # código para remover item
      remover_item()
      print("Removendo item...")
    case '7':
      # código para salvar
      json.dump(dados, open('Json_Aula_Python.json', 'w'), indent=4)
      print("Salvando...")
    case '8':
      # código para sair
      Saindo()
      print("Saindo...")

    case _:
      print("Opção inválida.")

def Saindo():
  print("Obrigado por usar o programa!")
  exit()

def ver_restaurante():
  restaurante = input("Digite o nome do restaurante: ")
  for item in dados: # Removed potential extra space before this line
    if item["Company"] == restaurante:
      print(item)

def ver_lanche():
 lanche = input("Digite o nome do lanche: ")
 for item in dados:
  if item["Item"] == lanche:
    print(item)

def adicionar_item():
  item = input("Digite o nome do item: ")
  preco = float(input("Digite o preço do item: "))
  company = input("Digite o nome da empresa:")
  descrição = input("Digite a descrição do item:")
  dados.append({"Item": item, "price": preco, "Company": company, "description": descrição})
  print("Item adicionado com sucesso!")
  return

def remover_item():
  item = input("Digite o nome do item que deseja remover: ")
  for i in range(len(dados)):
    if dados[i]["Item"] == item:
      del dados[i]
      print("Item removido com sucesso!")
      return

def main():
  nome_programa()
  while True:
    exibir_opçoes()
    menu()

print(main())